# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0002_auto_20170213_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='first_img',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='second_img',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='third_img',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
